name: elevation_extractor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.17.6 <3.0.0'

# Add regular dependencies here.
dependencies:
  image: ^4.0.17

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
